"""Generate compact 3D coordinates for the landing-page embedding graphic.

The source database and UNI weights stay local/ignored. This script exports only
normalized 2D coordinates and palette tones, so the landing page does not ship
model weights or the original embedding vectors.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sqlite3

import numpy as np
from sklearn.manifold import TSNE


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_DATABASE = PROJECT_ROOT / "data" / "mhist" / "uni_embeddings.sqlite3"
DEFAULT_OUTPUT = PROJECT_ROOT / "src" / "landing" / "embeddingProjection.ts"
EMBEDDING_DIMENSION = 1024


def load_rows(database: Path, count: int, seed: int) -> list[tuple[str, str, np.ndarray]]:
    with sqlite3.connect(database) as connection:
        rows = connection.execute(
            """
            SELECT image_name, proxy_priority, embedding, embedding_dimension
            FROM embeddings
            WHERE status = 'complete'
            ORDER BY image_name
            """
        ).fetchall()

    grouped: dict[str, list[tuple[str, str, np.ndarray]]] = {}
    for image_name, priority, blob, dimension in rows:
        if int(dimension) != EMBEDDING_DIMENSION or blob is None:
            continue
        vector = np.frombuffer(blob, dtype=np.float32)
        if vector.shape != (EMBEDDING_DIMENSION,) or not np.isfinite(vector).all():
            continue
        grouped.setdefault(str(priority), []).append((image_name, str(priority), vector))

    if len(grouped) < 2:
        raise ValueError("Expected at least two MHIST proxy-priority groups.")

    rng = np.random.default_rng(seed)
    per_group = max(2, count // len(grouped))
    selected: list[tuple[str, str, np.ndarray]] = []
    for priority in sorted(grouped):
        group = grouped[priority]
        indices = rng.choice(len(group), size=min(per_group, len(group)), replace=False)
        selected.extend(group[int(index)] for index in sorted(indices))
    return selected[:count]


def generate(database: Path, count: int, seed: int, dimensions: int) -> str:
    rows = load_rows(database, count, seed)
    matrix = np.stack([row[2] for row in rows]).astype(np.float32, copy=False)
    coordinates = TSNE(
        n_components=dimensions,
        perplexity=min(18.0, max(5.0, (len(rows) - 1) / 3.0)),
        init="pca",
        learning_rate="auto",
        max_iter=750,
        random_state=seed,
    ).fit_transform(matrix)
    minimum = coordinates.min(axis=0)
    span = np.maximum(coordinates.max(axis=0) - minimum, 1e-8)
    normalized = (coordinates - minimum) / span

    points = []
    for (_, priority, _), (x, y, z) in zip(rows, normalized, strict=True):
        points.append(
            {
                "x": round(float(x), 4),
                "y": round(float(y), 4),
                "z": round(float(z), 4),
                "tone": "teal" if priority == "Review First" else "sage",
            }
        )

    payload = json.dumps(points, indent=2)
    return (
        "// Generated by scripts/generate_landing_projection.py from local MHIST UNI embeddings.\n"
        "// Coordinates are normalized 3D t-SNE output; raw embeddings and weights are not shipped.\n"
        "export type LandingProjectionTone = \"teal\" | \"sage\";\n\n"
        "export interface LandingProjectionPoint {\n"
        "  x: number;\n"
        "  y: number;\n"
        "  z: number;\n"
        "  tone: LandingProjectionTone;\n"
        "}\n\n"
        f"export const LANDING_PROJECTION_POINTS: LandingProjectionPoint[] = {payload};\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--database", type=Path, default=DEFAULT_DATABASE)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--count", type=int, default=64)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--dimensions", type=int, default=3, choices=(3,))
    args = parser.parse_args()
    if args.count < 10:
        raise ValueError("--count must be at least 10.")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generate(args.database, args.count, args.seed, args.dimensions), encoding="utf-8")
    print(f"Wrote {args.count} projection points to {args.output}")


if __name__ == "__main__":
    main()
